"""
Checkpoint Rules Engine.

Contains the validation-rule inventory used by the Offer Readiness QA Tool.
The source PDF contains rules 1-66, with rule 51 absent.
"""

_RULE_INDEX = [
    (1, "Site Search / Product Stack", "Product stack displayed"),
    (2, "Site Search / Product Stack", "Product stack text"),
    (3, "Site Search / Product Stack", "Spec sequence"),
    (4, "Site Search / Product Stack", "Processor"),
    (5, "Site Search / Product Stack", "Operating System"),
    (6, "Site Search / Product Stack", "Graphics"),
    (7, "Site Search / Product Stack", "Memory"),
    (8, "Site Search / Product Stack", "Storage"),
    (9, "Site Search / Product Stack", "Display"),
    (10, "Site Search / Product Stack", "Display option count"),
    (11, "Product Stack Visual / Content", "Product images"),
    (12, "Product Stack Visual / Content", "Copilot+ PC badge"),
    (13, "Product Stack Visual / Content", "Product title"),
    (14, "Product Stack Visual / Content", "Price"),
    (15, "Product Stack Visual / Content", "Delivery date"),
    (16, "Product Stack Visual / Content", "Delivery date threshold"),
    (
        17,
        "Search to Customize & Buy Cross-check",
        "Specs carry over correctly",
    ),
    (
        18,
        "Search to Customize & Buy Cross-check",
        "Processor cross-check",
    ),
    (
        19,
        "Search to Customize & Buy Cross-check",
        "Full spec cross-check",
    ),
    (20, "Configuration / Option", "Option-class sequence"),
    (21, "Configuration / Option", "Processor/CPU sequence"),
    (22, "Configuration / Option", "OS sequence"),
    (23, "Configuration / Option", "Graphics sequence"),
    (24, "Configuration / Option", "Downsell/default logic"),
    (25, "Configuration / Option", "OS default"),
    (26, "Operating System / Language", "OS-dependent language"),
    (27, "Operating System / Language", "Windows Home vs Pro"),
    (28, "Display", "Display/camera dependency"),
    (29, "Display", "No display downsell"),
    (30, "Display", "Resolution format"),
    (31, "Display", "Resolution consistency"),
    (32, "Display", "Display label vs resolution"),
    (33, "Localization", "Country labels"),
    (34, "Localization", "Keyboard localization"),
    (35, "Localization", "Power cord localization"),
    (36, "Localization", "Packaging regional label"),
    (37, "Localization", "Regulatory label"),
    (38, "Power Supply / Packaging", "Power supply dependency"),
    (39, "Power Supply / Packaging", "Dummy price"),
    (40, "Power Supply / Packaging", "Packaging type"),
    (41, "Power Supply / Packaging", "Packaging label"),
    (42, "Power Supply / Packaging", "Adapter/battery dependency"),
    (43, "Warranty / Services", "Base warranty"),
    (44, "Warranty / Services", "Hardware support upgrade"),
    (45, "Warranty / Services", "No warranty downsell"),
    (
        46,
        "Warranty / Services",
        "Dummy pricing - warranty duration/options",
    ),
    (47, "Warranty / Services", "Pricing availability"),
    (
        48,
        "Services Compatibility",
        "ProSupport Plus + Accidental Damage",
    ),
    (49, "Services Compatibility", "Option hiding"),
    (50, "Software", "McAfee dependency"),
    (52, "Software", "Autopilot visibility"),
    (53, "Software", "Autopilot tag ID"),
    (54, "Software", "Enterprise software compatibility"),
    (55, "Bundle & Save / Candy Aisle", "Coupon blurb"),
    (56, "Bundle & Save / Candy Aisle", "Pricing"),
    (57, "Bundle & Save / Candy Aisle", "Flyout image"),
    (58, "Bundle & Save / Candy Aisle", "Key tech specs"),
    (59, "Bundle & Save / Candy Aisle", "Offer identifier"),
    (60, "PLP", "Display size"),
    (61, "PLP", "Ratings/reviews"),
    (62, "PLP", "Starting price"),
    (63, "PLP", "Lowest-price rule"),
    (64, "PLP to Config", "Price carry-over"),
    (
        65,
        "Fixed Offer",
        "Same spec sequence as Search",
    ),
    (
        66,
        "Fixed Offer",
        "Spec value consistency",
    ),
]

CHECKPOINT_RULES = [
    {
        "id": rule_id,
        "category": category,
        "checkpoint": checkpoint,
        "expected": None,
        "logic": None,
        "why_it_matters": None,
        "severity": None,
        "status": "needs_rule_details",
    }
    for rule_id, category, checkpoint in _RULE_INDEX
]
